# Generated by Django 5.0.3 on 2024-06-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='user_id',
        ),
    ]
